<?php
define('RECAPTCHA_BACKEND', 'RETIRADO_PARA_PUBLICACAO');
define('RECAPTCHA_FRONTEND', 'RETIRADO_PARA_PUBLICACAO');
define('SMPT_HOST', 'HOSTNAME');
define('SMPT_EMAIL', 'EMAIL');
define('SMPT_PASSWORD', 'SMPT_PASSWORD');
?>
